/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "stm32f439xx.h"
#include "stm32f439xx_gpio_driver.h"
#include "stm32f439xx_spi_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(void){
	for(uint32_t i = 0; i < 500000/2 ; i++);
}

void GPIO_ButtonInit(){
	GPIO_Handle_t GpioBtn;
		memset(&GpioBtn, 0, sizeof(GPIO_Handle_t));

		// BUTTON CONFIGURATIONS
		GpioBtn.pGPIOx = GPIOC;
		GpioBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
		GpioBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
		GpioBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_OP_SPEED_FAST;
		GpioBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

		GPIO_PeriClockControl(GPIOC, ENABLE);
		GPIO_Init(&GpioBtn);
}


/*
 * configuring pins fr SPI2
 * NSS:		PB12
 * SCLK:	PB13
 * MISO:	PB14
 * MOSI:	PB15
 *
 * AF5 FOR ALL OF THEM
 */
void SPI2_GPIO_Init(void){
	GPIO_Handle_t SPIPins;
	memset(&SPIPins, 0 , sizeof(SPIPins));

	SPIPins.pGPIOx = GPIOB;
	SPIPins.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALT;
	SPIPins.GPIO_PinConfig.GPIO_PinAltFunMode = 5;
	SPIPins.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	SPIPins.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	SPIPins.GPIO_PinConfig.GPIO_PinSpeed = GPIO_OP_SPEED_FAST;

	GPIO_PeriClockControl(GPIOB, ENABLE);

	// NSS
	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	GPIO_Init(&SPIPins);

	//SCLK
	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GPIO_Init(&SPIPins);

	//  MISO
	//SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;
	//GPIO_Init(&SPIPins);

	// MOSI
	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
	GPIO_Init(&SPIPins);

}

void SPI2_Init(void){
	SPI_Handle_t SPI2Handle;
	memset(&SPI2Handle, 0 , sizeof(SPI2Handle));

	SPI2Handle.pSPIx = SPI2;
	SPI2Handle.SPIConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;
	SPI2Handle.SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FD;
	SPI2Handle.SPIConfig.SPI_DFF = SPI_DFF_8BIT;
	SPI2Handle.SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV8;		// SCLK of 8MHz
	SPI2Handle.SPIConfig.SPI_CPOL = SPI_CPOL_LOW;
	SPI2Handle.SPIConfig.SPI_CPHA = SPI_CPHA_FIRST;
	SPI2Handle.SPIConfig.SPI_SSM = SPI_SSM_DI;						// HARDWARE SLAVE MANAGEMENT

	SPI_PeriClockControl(SPI2, ENABLE);
	SPI_Init(&SPI2Handle);
}

int main(void)
{
	char user_data[] = "Hello world";

	GPIO_ButtonInit();

	SPI2_GPIO_Init();
	SPI2_Init();

	SPI_SSOEConfig(SPI2, ENABLE);


	while( ! GPIO_ReadPin(GPIOC, GPIO_PIN_NO_13));

	delay();

	// enabling SPI peripheral
	SPI_PeripheralControl(SPI2, ENABLE);

	// sending the length information
	uint8_t datalen = strlen(user_data);
	SPI_SendData(SPI2, &datalen, 1);

	SPI_SendData(SPI2, (uint8_t*)user_data, strlen(user_data));

	// confirming if SPI not busy
	while (SPI_GetFlagStatus(SPI2, SPI_BSY_FLAG));

	// Disabling SPI peripheral
	SPI_PeripheralControl(SPI2, DISABLE);

    /* Loop forever */
	while(1);
}
